spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    user:
      name: admin
      password: admin
server:
  port: 8090

